### ISSUE TITLE
FALTA LOGICA PROPORCIONAL

### ISSUE THREAD

**Issue by Vell6z** [Franklin225/Venito_Camelas#1]
falta pa la ayuda del examen

**Comment by Franklin225** [comment]
Bueno

**Comment by Franklin225** [comment]
Mira mi rey https://github.com/Franklin225/Venito_Camelas/blob/master/Calculadora%20inteligente.py

**Comment by Vell6z** [comment]
[Literalmente la respuesta pero toca leer los comentarios del codigo](https://github.com/Franklin225/Venito_Camelas/blob/master/LogicaProporcional.py)
